import type { MetadataRoute } from "next";
import { cookies } from "next/headers";
import { DEFAULT_LOCALE, LOCALE_COOKIE, type Locale } from "@/lib/i18n/locale";
import { MESSAGES } from "@/lib/i18n/messages";

/**
 * PWA / installability manifest. Next auto-injects the matching
 * `<link rel="manifest">` into <head> because this file uses the
 * `manifest` metadata-route convention.
 *
 * Locale-aware: reads the same `oc-locale` cookie as layout.tsx so the
 * install prompt name / description match what the visitor sees. Icons
 * point at the dynamic icon routes generated by app/icon.tsx and
 * app/apple-icon.tsx.
 */
export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const v = (await cookies()).get(LOCALE_COOKIE)?.value;
  const locale: Locale = v === "zh" || v === "en" ? v : DEFAULT_LOCALE;
  const m = MESSAGES[locale].meta;

  return {
    name: m.titleDefault,
    short_name: "OC-Review",
    description: m.description,
    lang: m.htmlLang,
    start_url: "/",
    display: "standalone",
    background_color: "#faf9f5",
    theme_color: "#141413",
    icons: [
      { src: "/icon", sizes: "32x32", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
